### ISSUE TITLE
Turn pipeline configuration on its head

### ISSUE THREAD

**Issue by padovan** [kernelci/kernelci-pipeline#1048]
Today the [pipeline config](https://github.com/kernelci/kernelci-pipeline/blob/main/config/pipeline.yaml) is somewhat convoluted with configuration for a given tree every across a huge file.  We should try to improve this situation. And it will certainly require multiples steps, but below is an envisioned future state of a `trees.yaml` file that contains all trees and the main filters we have to apply when testing (eg architectures to build or hardware to test on).

```
trees:
    mainline:
        url: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git'
        branches:
            - "mainline" 
        architectures:
            - "all"
    mediatek:
        url: 'https://git.kernel.org/pub/scm/linux/kernel/git/mediatek/linux.git'
        branches:
            - "for-next"
            - "for-mailine"
        architectures:
            - "arm64"
            - "arm"
        platforms:
            mach: # or tag?
                - "mediatek"
```

The first step can be simply integrating branches into trees and then generate the build configs from there, leaving filters for a second step.

```
trees:
    mainline:
        url: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git'
        branches:
            - "mainline"
```
