### ISSUE TITLE
Pipeline job configuration

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-pipeline#217]
The `runner.py` service implemented during the initial PoC phase has lots of hard-coded assumptions to start `kver` or `kunit` tests when a `checkout` node becomes available.  This kind of dependencies between jobs should be defined in the YAML pipeline instead, at least with something semantically equivalent to `parent: <job-name>`.  Then we could have something like this:

```yaml
jobs:
  checkout:
    description: "Kernel source code checkout"
    runtime: shell
  kunit:
    description: "KUnit tests"
    runtime: k8s
    parent: checkout
  kernel-build:
    description: "Kernel build"
    runtime: k8s
    parent: checkout
  baseline:
    description: "Baseline tests with dmesg and bootrr"
    runtime: lava
    parent: kernel-build
```

This is of course over-simplified, and each job should have parallel instances being generated e.g. each checkout will result in multiple builds and each build multiple tests etc.  The example is just to illustrate the basic concepts.
