### ISSUE TITLE
tarball - 

### ISSUE THREAD

**Issue by yurinnick** [kernelci/kernelci-pipeline#296]
Tarball service fails to find SSH credentials unless explicitly specified:
```
kernelci-pipeline-tarball             | 08/01/2023 12:50:16 AM UTC [INFO] Uploading /home/kernelci/data/output/linux-mainline-master-v6.5-rc4-1-g45b7d7534050.tar.gz
kernelci-pipeline-tarball             | 08/01/2023 12:50:16 AM UTC [INFO] Connected (version 2.0, client OpenSSH_8.4p1)
kernelci-pipeline-tarball             | 08/01/2023 12:50:16 AM UTC [ERROR] Traceback (most recent call last):
kernelci-pipeline-tarball             |   File "/home/kernelci/pipeline/base.py", line 69, in run
kernelci-pipeline-tarball             |     status = self._run(context)
kernelci-pipeline-tarball             |   File "/home/kernelci/./pipeline/tarball.py", line 168, in _run
kernelci-pipeline-tarball             |     tarball_url = self._push_tarball(build_config, describe)
kernelci-pipeline-tarball             |   File "/home/kernelci/./pipeline/tarball.py", line 103, in _push_tarball
kernelci-pipeline-tarball             |     tarball_url = self._storage.upload_single((tarball_path, tarball_name))
kernelci-pipeline-tarball             |   File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/storage/__init__.py", line 57, in upload_single
kernelci-pipeline-tarball             |     self._upload([file_path], dest_path)
kernelci-pipeline-tarball             |   File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/storage/ssh.py", line 27, in _upload
kernelci-pipeline-tarball             |     ssh.connect(
kernelci-pipeline-tarball             |   File "/usr/local/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
kernelci-pipeline-tarball             |     self._auth(
kernelci-pipeline-tarball             |   File "/usr/local/lib/python3.10/site-packages/paramiko/client.py", line 819, in _auth
kernelci-pipeline-tarball             |     raise SSHException("No authentication methods available")
kernelci-pipeline-tarball             | paramiko.ssh_exception.SSHException: No authentication methods available
```

When specified with `--storage-cred` args, works as expected
```
  tarball:
    <<: *base-service
    container_name: 'kernelci-pipeline-tarball'
    command:
      - './pipeline/tarball.py'
      - '--settings=${SETTINGS:-/home/kernelci/config/kernelci.toml}'
      - 'run'
+      - '--storage-cred=/home/kernelci/data/ssh/id_rsa_tarball'
```
