### ISSUE TITLE
3-stage build job

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-pipeline#332]
During the discussion(https://github.com/kernelci/kernelci-pipeline/issues/330) of kbuild fragments we came to conclusion we need to implement 3-stage kernel build job:
1) Prepare job (generate config fragments, shell script with compile commands), run in kernelci/kernelci container
2) Compile job (compile kernel), run in compiler specific container
3) Complete job (upload artifacts, send notifications), run in kernelci/kernelci container

After initial investigation i found it is possible in k8s following way:

```
apiVersion: v1
kind: Pod
metadata:
  name: sequential-job
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  # these run sequentally
  initContainers:
  - name: job-1
    image: kernelci/kernelci
    command: ['sh', '-c', 'prepare-kbuild.sh','nodeid','jobid']
    volumeMounts:
      - name: shared-data
        mountPath: /generated
  - name: job-2
    image: kernelci/compiler-gcc2055.1
    command: ['sh', '-c', '/generated/compile.sh']
    volumeMounts:
      - name: shared-data
        mountPath: /generated
  # syntax require to have one from "containers"
  # it will run only after all initContainers are finished
  containers:
  - name: job-3
    image: kernelci/kernelci
    command: ['sh', '-c', 'complete.sh','nodeid','jobid']
    volumeMounts:
      - name: shared-data
        mountPath: /generated  
```

Ignore script names, type, nodeid and jobid, it is just example for now
