### ISSUE TITLE
Enable `BayLibre` lab in the pipeline

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-pipeline#446]
Enable one more lab for running tests in the pipeline i.e. BayLibre. 
We need to get the lab token and URL from the BayLibre team. Once we receive this information we can enable the lab referring the below checklist:

-  [ ] Add configurations to `config/pipeline.yaml` i.e. add an entry under `runtime`
-  [ ] Add lab-specific jobs to `config/pipeline.yaml` i.e. entries under `jobs`
-  [ ] Add scheduler configurations to `config/pipeline.yaml` i.e. an entry under `scheduler`
-  [ ] Add lab section to `kernelci.toml` 
-  [ ] Update `docker-compose.yaml` to submit tests to the lab 

Just for the reference, this is the `runtime-config` entry in the legacy system for baylibre.
```
  lab-baylibre:
    lab_type: legacy.lava_xmlrpc
    url: 'https://lava.baylibre.com/RPC2/'
    queue_timeout:
      days: 1
    filters:
      - regex: {'tree': '^(kernelci|mainline|next|stable|arm64|riscv|soc|amlogic|matthiasbgg)$'}
      - passlist:
          plan:
            - baseline
            - kselftest
            - preempt-rt
            - ltp
```

**Comment by khilman** [comment]
Assigned to @montjoie who can help get this setup for BayLibre.

**Comment by a-wai** [comment]
FWIW, with https://github.com/kernelci/kernelci-core/pull/2413 the `runtimes` entry would probably look like this:
```yaml
  lava-baylibre:
    lab_type: lava
    url: 'https://lava.baylibre.com/RPC2/'
    notify:
      callback:
        token: kernelci-api-token-staging
        url: https://staging.kernelci.org:9100
    rules:
      tree:
      - kernelci
      - mainline
      - next
      # The following trees are not configured in the new pipeline (yet)
      - stable
      - arm64
      - riscv
      - soc
      - amlogic
      - matthiasbgg
```

The test plans passlist isn't needed anymore, as `scheduler` entries take care of assigning each job to a specific runtime, so you only need to ensure those entries only cover the jobs you want to run on this lab.

Also, I don't think the `queue_timeout` parameter can be handled yet with the new system.
