### ISSUE TITLE
Set job priority from runtime configuration

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-pipeline#513]
Enable setting job `priority` from the `runtime` configuration in the `config/pipeline.yaml`.

Legacy system has 3 fields for setting job priority in the lab configuration i.e. `priority`, `priority_min` , and `priority_max`.
Enable the same in the new system:
```
lava-baylibre:
    lab_type: lava
    url: 'https://lava.baylibre.com/'
    priority_min: 50
    priority_max: 70
    notify:
      callback:
        token: kernelci-new-api
        url: https://staging.kernelci.org:9100
```
