### ISSUE TITLE
Enable 'discoverable devices probe' kselftest on MediaTek Chromebooks

### ISSUE THREAD

**Issue by nfraprado** [kernelci/kernelci-pipeline#579]
This task is to track progress on enabling the [discoverable devices probe kselftest](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=dacf1d7a78bf8a131346c47bfba7fe1f3ff44beb) on all MediaTek Chromebooks.

**Comment by nfraprado** [comment]
I've put together the test definitions for the platforms:

`google,tomato.yaml`:
```
# SPDX-License-Identifier: GPL-2.0
- type: usb-controller
  dt-mmio: 112a0000
  usb-version: 2
  devices:
    - path: 1
      interfaces: [0, 1]
      name: camera
- type: usb-controller
  dt-mmio: 112b0000
  usb-version: 2
  devices:
    - path: 1
      interfaces: [0, 1]
      name: bluetooth
- type: pci-controller
  dt-mmio: 112f8000
  devices:
    - path: 0.0/0.0
      name: wifi
```
(LAVA run: https://lava.collabora.dev/scheduler/job/13713188)

`google,juniper.yaml`:
```
# SPDX-License-Identifier: GPL-2.0
- type: usb-controller
  dt-mmio: 11200000
  usb-version: 2
  devices:
    - path: 1.3
      interfaces: [0, 1]
      name: camera
```
(LAVA run: https://lava.collabora.dev/scheduler/job/13713523)

Note: On Juniper and Steelix the WIFI and Bluetooth are wired through SDIO (MMC controller), so they're tested by the DT kselftest.

`google,steelix.yaml`:
```
# SPDX-License-Identifier: GPL-2.0
- type: usb-controller
  dt-mmio: 11200000
  usb-version: 2
  devices:
    - path: 1
      interfaces: [0, 1]
      name: camera1
- type: usb-controller
  dt-mmio: 11280000
  usb-version: 2
  devices:
    - path: 1.3
      interfaces: [0, 1]
      name: camera2
```
(LAVA run: https://lava.collabora.dev/scheduler/job/13713399)

Note: To confirm, are there really two cameras or why are there two different devices binding to uvcvideo? And should the usbhid device be tested too? (the vendor is realtek)

`google,spherion.yaml` is provided upstream as an example.

Now what remains is to create a repository to host these files and make the test fetch them.
